# Generated by Django 5.0.2 on 2024-02-13 19:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='question',
            new_name='post',
        ),
    ]
